---
extends:
  - "standard"
  - "plugin:markdown/recommended"
plugins: [markdown]
rules:
  no-unused-vars: 0
  eqeqeq: 0
  no-undef: 0
  no-extend-native: 0
  prefer-const: 0 # we need to be able to misuse this for illustrative purposes
